"""empty message

Revision ID: d2752f2c5479
Revises: 
Create Date: 2022-11-04 18:35:51.337359

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = 'd2752f2c5479'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('black_list_signs',
    sa.Column('uuid', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_black_list_signs_name'), 'black_list_signs', ['name'], unique=True)
    op.create_table('black_lists',
    sa.Column('uuid', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dt', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('inn', sa.String(length=512), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=False),
    sa.Column('sites', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('sign', sa.Integer(), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sign'], ['black_list_signs.id'], name='fk_black_lists_black_list_signs_id_sign'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_black_lists_inn'), 'black_lists', ['inn'], unique=False)
    op.create_index(op.f('ix_black_lists_name'), 'black_lists', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_black_lists_name'), table_name='black_lists')
    op.drop_index(op.f('ix_black_lists_inn'), table_name='black_lists')
    op.drop_table('black_lists')
    op.drop_index(op.f('ix_black_list_signs_name'), table_name='black_list_signs')
    op.drop_table('black_list_signs')
    # ### end Alembic commands ###
